apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/argoproj/argo-events/manifests/base?ref=v1.4.1
- github.com/argoproj/argo-events/manifests/cluster-install/rbac?ref=v1.4.1
resources:
  - namespace.yaml
  - event-bus.yaml
patchesStrategicMerge:
- rbac.yaml
namespace: argo-events